name: "Build Nix"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: DeterminateSystems/nix-installer-action@v2

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build
        run: nix build #.